<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Общая-информация" data-toc-modified-id="Общая-информация-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Общая информация</a></span></li><li><span><a href="#Подготовка-данных" data-toc-modified-id="Подготовка-данных-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Подготовка данных</a></span><ul class="toc-item"><li><span><a href="#Обработка-пропусков,-изменение-типов-данных" data-toc-modified-id="Обработка-пропусков,-изменение-типов-данных-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Обработка пропусков, изменение типов данных</a></span></li><li><span><a href="#Расчет-суммарных-продаж-во-всех-регионах,-создание-отдельного-столбца" data-toc-modified-id="Расчет-суммарных-продаж-во-всех-регионах,-создание-отдельного-столбца-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Расчет суммарных продаж во всех регионах, создание отдельного столбца</a></span></li></ul></li><li><span><a href="#Исследовательский-анализ-данных" data-toc-modified-id="Исследовательский-анализ-данных-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Исследовательский анализ данных</a></span><ul class="toc-item"><li><span><a href="#Количество-игр,-выпущенных-в-разные-годы" data-toc-modified-id="Количество-игр,-выпущенных-в-разные-годы-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Количество игр, выпущенных в разные годы</a></span></li><li><span><a href="#Платформы-с-наибольшими-суммарными-продажами" data-toc-modified-id="Платформы-с-наибольшими-суммарными-продажами-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Платформы с наибольшими суммарными продажами</a></span></li><li><span><a href="#Выбираем-несколько-потенциально-прибыльных-платформ" data-toc-modified-id="Выбираем-несколько-потенциально-прибыльных-платформ-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Выбираем несколько потенциально прибыльных платформ</a></span></li><li><span><a href="#График-«ящик-с-усами»-по-глобальным-продажам-игр-в-разбивке-по-платформам" data-toc-modified-id="График-«ящик-с-усами»-по-глобальным-продажам-игр-в-разбивке-по-платформам-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>График «ящик с усами» по глобальным продажам игр в разбивке по платформам</a></span></li><li><span><a href="#Как-влияют-на-продажи-внутри-одной-популярной-платформы-отзывы-пользователей-и-критиков" data-toc-modified-id="Как-влияют-на-продажи-внутри-одной-популярной-платформы-отзывы-пользователей-и-критиков-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Как влияют на продажи внутри одной популярной платформы отзывы пользователей и критиков</a></span></li><li><span><a href="#Сравнение-выводов-с-продажами-игр-на-других-платформах" data-toc-modified-id="Сравнение-выводов-с-продажами-игр-на-других-платформах-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Сравнение выводов с продажами игр на других платформах</a></span></li><li><span><a href="#Общее-распределение-игр-по-жанрам" data-toc-modified-id="Общее-распределение-игр-по-жанрам-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Общее распределение игр по жанрам</a></span></li></ul></li><li><span><a href="#Портрет-пользователя-каждого-региона" data-toc-modified-id="Портрет-пользователя-каждого-региона-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Портрет пользователя каждого региона</a></span><ul class="toc-item"><li><span><a href="#Самые-популярные-платформы-в-регионах" data-toc-modified-id="Самые-популярные-платформы-в-регионах-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Самые популярные платформы в регионах</a></span></li><li><span><a href="#Самые-популярные-жанры-в-регионах" data-toc-modified-id="Самые-популярные-жанры-в-регионах-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Самые популярные жанры в регионах</a></span></li><li><span><a href="#Влияние-рейтинга-ESRB-на-продажи-в-отдельном-регионе" data-toc-modified-id="Влияние-рейтинга-ESRB-на-продажи-в-отдельном-регионе-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Влияние рейтинга ESRB на продажи в отдельном регионе</a></span></li></ul></li><li><span><a href="#Проверка-гипотезы" data-toc-modified-id="Проверка-гипотезы-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Проверка гипотезы</a></span><ul class="toc-item"><li><span><a href="#Средние-пользовательские-рейтинги-платформ-Xbox-One-и-PC-одинаковые" data-toc-modified-id="Средние-пользовательские-рейтинги-платформ-Xbox-One-и-PC-одинаковые-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Средние пользовательские рейтинги платформ Xbox One и PC одинаковые</a></span></li><li><span><a href="#Средние-пользовательские-рейтинги-жанров-Action-и-Sports-разные" data-toc-modified-id="Средние-пользовательские-рейтинги-жанров-Action-и-Sports-разные-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Средние пользовательские рейтинги жанров Action и Sports разные</a></span></li></ul></li><li><span><a href="#Общий-вывод" data-toc-modified-id="Общий-вывод-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Общий вывод</a></span></li></ul></div>

# Исследование данных о продажах компьютерных игр

**Описание проекта**

Интернет-магазин «Стримчик» продаёт по всему миру компьютерные игры. Из открытых источников доступны исторические данные по 2016 год о продажах игр, оценки пользователей и экспертов, жанры и платформы (например, Xbox или PlayStation). 

Задача: выявить определяющие успешность игры закономерности. Это позволит сделать ставку на потенциально популярный продукт и спланировать рекламные кампании.

**План исследования**

**1. Изучить данные файла и общую информацию**


**2. Подготовить данные**
- Привести названия столбцов к нижнему регистру

- Преобразовать данные в нужные типы

- Обработать пропуски при необходимости

- Посчитать суммарные продажи во всех регионах, записать их в отдельный столбец

**3. Провести исследовательский анализ данных**

- Сколько игр выпускалось в разные годы, важны ли данные за все периоды?

- Как менялись продажи по платформам. Выбрать платформы с наибольшими суммарными продажами и построить распределение по годам. За какой характерный срок появляются новые и исчезают старые платформы?

- Выбрать данные за соответствующий актуальный период. Актуальный период определить в результате исследования предыдущих вопросов. Основной фактор — эти данные помогут построить прогноз на 2017 год

- Не учитывать в работе данные за предыдущие годы

- Какие платформы лидируют по продажам, растут или падают? Выбрать несколько потенциально прибыльных платформ

- Построить график «ящик с усами» по глобальным продажам игр в разбивке по платформам. Сделать выводы

- Сравнить, как влияют на продажи внутри одной популярной платформы отзывы пользователей и критиков. Построить диаграмму рассеяния и посчитать корреляцию между отзывами и продажами. Сформулировать выводы

- Соотнести выводы с продажами игр на других платформах

- Проанализировать общее распределение игр по жанрам. Что можно сказать о самых прибыльных жанрах? Выделяются ли жанры с высокими и низкими продажами?

**4. Составить портрет пользователя каждого региона**

- Определить для пользователя каждого региона (NA, EU, JP):
Самые популярные платформы (топ-5). Описать различия в долях продаж.
Самые популярные жанры (топ-5). Пояснить разницу.
Влияет ли рейтинг ESRB на продажи в отдельном регионе?

**5. Проверить гипотезы**

- Средние пользовательские рейтинги платформ Xbox One и PC одинаковые
- Средние пользовательские рейтинги жанров Action и Sports разные

**6. Общий вывод**

**Описание данных**

*Name* — название игры

*Platform* — платформа

*Year_of_Release* — год выпуска

*Genre* — жанр игры

*NA_sales* — продажи в Северной Америке (миллионы проданных копий)

*EU_sales* — продажи в Европе (миллионы проданных копий)

*JP_sales* — продажи в Японии (миллионы проданных копий)

*Other_sales* — продажи в других странах (миллионы проданных копий)

*Critic_Score* — оценка критиков (максимум 100)

*User_Score* — оценка пользователей (максимум 10)

*Rating* — рейтинг от организации ESRB (англ. Entertainment Software Rating Board). Эта ассоциация определяет рейтинг компьютерных игр и присваивает им подходящую возрастную категорию.

*Этот рейтинг выглядит следующим образом:*

*E* - everyone подходит для всех возрастов

*E10+* - everyone 10+ для возраста от 10 лет

*T* - teen для возраста от 13 лет

*M* - mature 17+ для возраста от 17 лет

*AO* - adults only 18+ для возраста от 18 лет

*RP* - rating pending рейтинг ожидается, окончательный рейтинг еще не присвоен

*EC* - early childhood для возраста от 3 лет

*K-A* - kids to adults устаревшая категория, замененная с 01.01.1998 на категорию Е

## Общая информация

In [1]:
import pandas as pd
from ydata_profiling import ProfileReport

import plotly
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)

from scipy import stats as st

In [2]:
try:
    data = pd.read_csv('C:\\Users\\1\\Downloads\\games.csv')
except:
    data = pd.read_csv('/datasets/games.csv')

In [3]:
data.head(10)

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
5,Tetris,GB,1989.0,Puzzle,23.20,2.26,4.22,0.58,NaN,NaN,NaN
6,New Super Mario Bros.,DS,2006.0,Platform,11.28,9.14,6.50,2.88,89.0,8.5,E
7,Wii Play,Wii,2006.0,Misc,13.96,9.18,2.93,2.84,58.0,6.6,E
8,New Super Mario Bros. Wii,Wii,2009.0,Platform,14.44,6.94,4.70,2.24,87.0,8.4,E
9,Duck Hunt,NES,1984.0,Shooter,26.93,0.63,0.28,0.47,NaN,NaN,NaN

In [4]:
profile = ProfileReport(data, title="Отчет о датасете", explorative=True)

In [5]:
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

- **11 переменных** (столбцов), **5 переменных** категориальных, тип данных **object**, **6 переменных** вещественных, тип данных **float64**. **16715 наблюдений** (строк), всего **пропусков в ячейках** по датасету **12,1%**. **Полных дубликатов нет**.

- ***Year_of_Release*** — год выпуска:

Датасет охватывает временной интервал начиная **с 1980 года по 2016 год** включительно. *Тип данных float64*, 37 уникальных значений, **1.6% пропусков**, нулевых значений нет. Распределение значений ассиметрично, имеет длинный "хвост" слева. Больше всего значений с 2006 по 2011 год. Высокая корреляция с Platform и User_Score.

- ***Name*** — название игры:

тип данных object, **2 пропущенных значения**, 11559 уникальных значений. Обе игры без названия выпущены в 1993 году, общие продажи по одной составляют 2,39 млн. копий, по второй 30 тыс. копий, проданных в Японии.

In [6]:
data.query('Name.isna()')

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
659,NaN,GEN,1993.0,NaN,1.78,0.53,0.00,0.08,NaN,NaN,NaN
14244,NaN,GEN,1993.0,NaN,0.00,0.00,0.03,0.00,NaN,NaN,NaN

- ***Platform*** — платформа:

тип object, 31 уникальное значение, **пропусков нет**. Чаще всего встречаются PS2 - 12.9%, DS - 12.9%, PS3 - 8.0%, Wii - 7.9%, X360 - 7.6%. Высокая корреляция с Year_of_Release и User_Score.

- ***Genre*** — жанр игры:

тип object, 12 уникальных значений, **2 пропуска**, в тех же строках, где не указано название игры. Чаще всего встречаются Action - 20.2%, Sports - 14.0%, Misc - 10.5%, Role-Playing - 9.0%, Shooter - 7.9%, Adventure - 7.8%, Racing - 7.5%. Высокая корреляция с Rating.

- ***NA_sales*** — продажи в Северной Америке *(миллионы проданных копий)*:

тип данных float64, **пропусков нет**, 27.0% нулевых значений. Высокая корреляция с EU_sales, JP_sales, Other_sales. Распределение значений ассиметрично и скошено справа.

- ***EU_sales*** — продажи в Европе *(миллионы проданных копий)*:

тип float64, **пропусков нет**, 35.1% нулевых значений. Высокая корреляция с NA_sales, JP_sales, Other_sales. Распределение значений ассиметрично и скошено справа.

- ***JP_sales*** — продажи в Японии *(миллионы проданных копий)*:

тип float64, **пропусков нет**, 62.9% нулевых значений. Высокая корреляция с NA_sales, EU_sales. Распределение значений ассиметрично и скошено справа.

- ***Other_sales*** — продажи в других странах *(миллионы проданных копий)*:

тип float64, **пропусков нет**, 39.5% нулевых значений. Высокая корреляция с NA_sales, EU_sales. Распределение значений ассиметрично и скошено справа.

- ***Critic_Score*** — оценка критиков *(максимум 100)*:

тип float64, **пропусков 51.3%**, *нулевых значений нет*. Высокая корреляция с User_Score. Распределение значений ассиметрично и скошено слева. Чаще всего встречаются значения от 70 до 80.

- ***User_Score*** — оценка пользователей *(максимум 10)*:

*тип данных определен как object*, скорее всего в связи с наличием строковых значений *'tbd' - 14.5%, также есть одно "нулевое" значение*. **Пропусков 40.1%**. Высокая корреляция с Platform, Year_of_Release и Critic_Score.

*аббревиатура tbd* - to be decided or to be determined, "подлежит определению" фактически означает отсутствие рейтига.

In [7]:
data.query('User_Score=="0"')

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
2835,My Little Pony: Pinkie Pie's Party,DS,2008.0,Adventure,0.66,0.0,0.0,0.06,NaN,0,E

- ***Rating*** — возрастной рейтинг от *американской организации ESRB*:

тип данных object, **40.5% пропусков**, 8 уникальных значений. Чаще всего встречаются игры категории E - 23.9%, T - 17.7%, M - 9.4%, E10+ - 8.5%. Высокая корреляция с  Genre.

In [8]:
data.query('Rating=="K-A"')

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
656,Theme Hospital,PC,1997.0,Strategy,2.30,0.10,0.00,0.00,NaN,9,K-A
903,PaRappa The Rapper,PS,1996.0,Misc,0.26,0.16,1.46,0.03,92.0,7.4,K-A
16681,Worms 2,PC,1997.0,Strategy,0.00,0.01,0.00,0.00,NaN,8.1,K-A

In [9]:
data.query('Rating=="RP"')

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
13672,Clockwork Empires,PC,NaN,Strategy,0.0,0.04,0.0,0.00,58.0,3.8,RP
14270,Supreme Ruler: Cold War,PC,2011.0,Strategy,0.0,0.03,0.0,0.01,63.0,6.8,RP
16180,WRC: FIA World Rally Championship,PC,NaN,Racing,0.0,0.01,0.0,0.00,65.0,NaN,RP

## Подготовка данных

### Обработка пропусков, изменение типов данных

In [10]:
#Приведем названия колонок к нижнему регистру

data.columns = data.columns.str.lower()

In [11]:
#Визуализация % пропусков в колонках

missing_values = (data.isna().mean()*100).round(2).sort_values()  

trace = go.Bar(
    x=missing_values.values,
    y=missing_values.index,
    marker_color='crimson',
    orientation = 'h',
    text=missing_values.apply(lambda x: '{}%'.format(x)),           
    textposition='auto',
    hoverinfo='x+y')

layout = {'title': 'Количество пропусков в данных по колонкам датасета, %',
          'xaxis': {'title': 'количество пропусков, %'},
          'yaxis': {'title': 'название колонки'}}
         
fig = go.Figure(data=trace, layout=layout)
fig.show()

In [12]:
#Игры, у которых отсутствует оценка критиков, пользователей и рейтинг ESRB по годам

missing_scores_rating = data.query('critic_score.isna() and user_score.isna() and rating.isna()'
                                  ).year_of_release.reset_index()

trace = go.Histogram(
    x=missing_scores_rating.year_of_release,
    marker_color='lightseagreen',
    nbinsx=100)

layout = {'title': 'Игры, у которых отсутствует оценка критиков, пользователей и рейтинг ESRB по годам',
          'xaxis': {'title': 'год'},
          'yaxis': {'title': 'количество пропусков'}}
         
fig = go.Figure(data=trace, layout=layout)
fig.show()

In [13]:
#Платформы, у которых отсутствуют данные о дате релиза

missing_year_platforms = data.query('year_of_release.isna()').platform.reset_index()

trace = go.Histogram(
    x=missing_year_platforms.platform,
    marker_color='lightseagreen',
    nbinsx=100)

layout = {'title': 'Платформы, у которых отсутствуют данные о дате релиза',
          'xaxis': {'title': 'название платформы'},
          'yaxis': {'title': 'количество пропусков'}}
         
fig = go.Figure(data=trace, layout=layout)
fig.show()

In [14]:
#Жанры, у которых отсутствуют данные о дате релиза

missing_year_genres = data.query('year_of_release.isna()').genre.reset_index()

trace = go.Histogram(
    x=missing_year_genres.genre,
    marker_color='lightseagreen',
    nbinsx=100)

layout = {'title': 'Жанры, у которых отсутствуют данные о дате релиза',
          'xaxis': {'title': 'название жанра'},
          'yaxis': {'title': 'количество пропусков'}}
         
fig = go.Figure(data=trace, layout=layout)
fig.show()

Игры, которые не имеют оценок критиков и пользователей, а также возрастной рейтинг есть за каждый год исследуемых данных. Можно предположить, что в любом случае, независимо от возможности оценить игру и присвоить ей рейтинг, каждый год какой-то процент игр остается без оценок, причем, чем больше игр выходит за год, тем больше игр остается без оценок. Кроме того, помимо американского рейтинга ESRB, например в Европе, Японии, Австралии и т.д. есть свои рейтинговые организации.

Данные о дате релиза отсутствуют как для наиболее популярных платформ PS2, DS, PS3, Wii, X360 и жанров Action, Sports, Misc, Role-Playing, Shooter, Adventure, Racing, так и для менее популярных. Также, игры на разных платформах могут иметь разную дату релиза и разные оценки. В названиях некоторых игр, таких как Madden NFL 2002, Madden NFL 2004, PDC World Championship Darts 2008, NASCAR Thunder 2003, FIFA Soccer 2004 и т.д., обозначен год, однако это не означает, что игра на этой платформе вышла в этом году. Заполнение пропусков искусственными значениями, медианой и средним, не очень хорошая идея, и может привести к искажению данных. Поэтому используем заглушки:

оценки критиков не имеют нулевых значений, оценки пользователей имеют одно нулевое значение; для удобства и чтобы не было путаницы, пусть отсутствие оценки будет обозначено как -1,

пропуски в рейтинге как no rating,

пропуски в названии игры и жанре удаляем,

пропуски даты релиза удаляем.

In [15]:
#Обрабатываем пропуски в оценках критиков

data['critic_score'] = data['critic_score'].fillna(-1)

In [16]:
#Обрабатываем пропуски в оценках пользователей

data['user_score'] = pd.to_numeric(data['user_score'], errors='coerce').fillna(-1)

In [17]:
#Пропуски в рейтинге

data['rating'] = data['rating'].fillna('no rating')

In [18]:
#Удаляем пропуски в названии игры (в этих строках пропуск жанра)

data = data[~(data['name'].isna())]

In [19]:
#Удаляем пропуски года выпуска

data = data[~(data['year_of_release'].isna())]

In [20]:
#Пребразуем тип данных года в целочисленный

data['year_of_release'] = data['year_of_release'].astype('int64')

In [21]:
#Замена старого рейтинга новым обозначением

data = data.replace(to_replace = 'K-A', value = 'E', regex = True)

In [22]:
#Выведем общую информацию

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16444 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16444 non-null  object
 1   platform         16444 non-null  object
 2   year_of_release  16444 non-null  int64
 3   genre            16444 non-null  object
 4   na_sales         16444 non-null  float64
 5   eu_sales         16444 non-null  float64
 6   jp_sales         16444 non-null  float64
 7   other_sales      16444 non-null  float64
 8   critic_score     16444 non-null  float64
 9   user_score       16444 non-null  float64
 10  rating           16444 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 1.5+ MB

### Расчет суммарных продаж во всех регионах, создание отдельного столбца

In [23]:
#Создаем новый столбец 'total_sales', который суммирует все продажи по строке

data.insert(loc=8, column='total_sales', value=data[['na_sales', 'eu_sales', 'jp_sales', 'other_sales']].sum(axis = 1))

In [24]:
data.head()

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,total_sales,critic_score,user_score,rating
0,Wii Sports,Wii,2006,Sports,41.36,28.96,3.77,8.45,82.54,76.0,8.0,E
1,Super Mario Bros.,NES,1985,Platform,29.08,3.58,6.81,0.77,40.24,-1.0,-1.0,no rating
2,Mario Kart Wii,Wii,2008,Racing,15.68,12.76,3.79,3.29,35.52,82.0,8.3,E
3,Wii Sports Resort,Wii,2009,Sports,15.61,10.93,3.28,2.95,32.77,80.0,8.0,E
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,11.27,8.89,10.22,1.00,31.38,-1.0,-1.0,no rating

In [25]:
#Проверка пропусков

temp = data.copy() 
list_c = ['name', 'platform', 'year_of_release', 'genre', 'critic_score', 'user_score', 'rating']
print(temp.info())
for col_l in list_c:
  print('-'* 25)
  print(col_l, temp[col_l].sort_values().unique())
  print(col_l,': кол-во NaN',temp[col_l].isna().sum(),
        ', процент NaN', round(temp[col_l].isna().sum()/len(temp)*100, 2),'%')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16444 entries, 0 to 16714
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16444 non-null  object
 1   platform         16444 non-null  object
 2   year_of_release  16444 non-null  int64
 3   genre            16444 non-null  object
 4   na_sales         16444 non-null  float64
 5   eu_sales         16444 non-null  float64
 6   jp_sales         16444 non-null  float64
 7   other_sales      16444 non-null  float64
 8   total_sales      16444 non-null  float64
 9   critic_score     16444 non-null  float64
 10  user_score       16444 non-null  float64
 11  rating           16444 non-null  object
dtypes: float64(7), int64(1), object(4)
memory usage: 1.6+ MB
None
-------------------------
name [' Beyblade Burst' ' Fire Emblem Fates' " Frozen: Olaf's Quest" ...
 'uDraw Studio' 'uDraw Studio: Instant Artist'
 '¡Shin Chan Flipa en colores!']
name : кол-во NaN 0 , процент NaN 0.0 %
-------------------------
platform ['2600' '3DO' '3DS' 'DC' 'DS' 'GB' 'GBA' 'GC' 'GEN' 'GG' 'N64' 'NES' 'NG'
 'PC' 'PCFX' 'PS' 'PS2' 'PS3' 'PS4' 'PSP' 'PSV' 'SAT' 'SCD' 'SNES' 'TG16'
 'WS' 'Wii' 'WiiU' 'X360' 'XB' 'XOne']
platform : кол-во NaN 0 , процент NaN 0.0 %
-------------------------
year_of_release [1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993
 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007
 2008 2009 2010 2011 2012 2013 2014 2015 2016]
year_of_release : кол-во NaN 0 , процент NaN 0.0 %
-------------------------
genre ['Action' 'Adventure' 'Fighting' 'Misc' 'Platform' 'Puzzle' 'Racing'
 'Role-Playing' 'Shooter' 'Simulation' 'Sports' 'Strategy']
genre : кол-во NaN 0 , процент NaN 0.0 %
-------------------------
critic_score [-1. 13. 17. 19. 20. 21. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34.
 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52.
 53. 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70.
 71. 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88.
 89. 90. 91. 92. 93. 94. 95. 96. 97. 98.]
critic_score : кол-во NaN 0 , процент NaN 0.0 %
-------------------------
user_score [-1.   0.   0.2  0.3  0.5  0.6  0.7  0.9  1.   1.1  1.2  1.3  1.4  1.5
  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9
  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3
  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5  5.6  5.7
  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9  7.   7.1
  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3  8.4  8.5
  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7]
user_score : кол-во NaN 0 , процент NaN 0.0 %
-------------------------
rating ['AO' 'E' 'E10+' 'EC' 'M' 'RP' 'T' 'no rating']
rating : кол-во NaN 0 , процент NaN 0.0 %

## Исследовательский анализ данных

Представим, что сейчас декабрь 2016 г., и мы планируем кампанию на 2017-й. 

- Сколько игр выпускалось в разные годы, важны ли данные за все периоды?
- За какой характерный срок появляются новые и исчезают старые платформы?
- Выбираем данные за соответствующий актуальный период. Актуальный период определим в результате исследования предыдущих вопросов. Основной фактор — эти данные помогут построить прогноз на 2017 год.
- **В работе не будут учитываться данные за предыдущие годы.**

### Количество игр, выпущенных в разные годы

In [26]:
fig = px.bar(data.groupby('year_of_release').name.count(),
             color=data.groupby('year_of_release').name.count(), 
             text=data.groupby('year_of_release').name.count(),
             title='Количество игр по годам релиза с 1980 по 2016 год',
             labels={'color':'количество игр',
                     'value':'количество игр', 
                     'year_of_release': 'год релиза'})

fig.update_traces(hovertemplate = 'год релиза : %{x}<br>количество игр : %{y}',
                  textfont_size=8, textangle=0, 
                  textposition='outside')

fig.show()

In [27]:
fig = px.bar(data.groupby('year_of_release').total_sales.sum(), 
             color=data.groupby('year_of_release').total_sales.sum().round(2),
             title='Общие продажи в миллионах проданных копий по годам релиза с 1980 по 2016 год',
             labels={'value':'общие продажи, млн. копий', 
                     'year_of_release': 'год', 
                     'color':'общие продажи'})

fig.update_traces(hovertemplate = 'год релиза : %{x}<br>общие продажи, млн. копий : %{y}')

fig.show()

На 2008 - 2009 годы приходится максимально количество выпущенных игр, далее спад.

### Платформы с наибольшими суммарными продажами

- За какой характерный срок появляются новые и исчезают старые платформы?

In [28]:
all_years_platform_sales = data.groupby(['year_of_release', 'platform']).total_sales.sum().reset_index()

fig = go.Figure(data=go.Heatmap(name = 'Тепловая карта',
                   z = all_years_platform_sales.total_sales,
                   x = all_years_platform_sales.platform,
                   y = all_years_platform_sales.year_of_release,
                   hoverongaps = False, hoverinfo = 'x+y+z',
                   hovertemplate = 'платформа : %{x}<br>год : %{y}<br>общие продажи, млн. копий : %{z}'))

fig.update_layout(title='Тепловая карта общих продаж игр в разбивке по платформам с 1980 по 2016 год',
                  xaxis_title='платформа', 
                  yaxis_title="год")

fig.show()

Жизненный цикл платформы с момента выхода на рынок до вытеснения новым продуктом составляет примерно 9-10 лет.

Для того, чтобы построить прогноз на 2017 год, возьмем наиболее **актуальный период**, начиная **с 2013 года**.

In [29]:
data.groupby('platform').total_sales.sum().sort_values(ascending=False).reset_index().style.bar()

Выбираем первые 6 платформ с наибольшими суммарными продажами, для них построим распределение по годам.

In [30]:
top_platforms = data.groupby('platform').total_sales.sum().sort_values(ascending=False).head(6)

In [31]:
top_platforms_sales = data.query('platform in @top_platforms.index'
                                ).pivot_table(index='year_of_release', 
                                              columns='platform', 
                                              values='total_sales', 
                                              aggfunc='sum')

In [32]:
fig = px.line(top_platforms_sales, markers=True, symbol='platform',
              title='Распределение общих продаж для платформ с наибольшими продажами с 1980 по 2016 год',
              labels={'value':'общие продажи, млн. копий', 
                      'year_of_release': 'год', 
                      'platform':'платформа'})

fig.show()

На графике виден артефакт у платформы DS, что является ошибкой, так как в 1985 году этой платформы еще не существовало.

DS - с 2004 по 2013 год

PS - с 1994 по 2003 год

PS2 - с 2000 по 2011 год

PS3 - с 2006 по 2016 год

Wii - с 2006 по 2016 год

X360 - с 2005 по 2016 год

**Все последующие исследования выполняем для актуального периода.**

In [33]:
data = data[data['year_of_release'] >= 2013]

### Выбираем несколько потенциально прибыльных платформ 
- Какие платформы лидируют по продажам, растут или падают?

In [34]:
fig = px.line(data.pivot_table(index='year_of_release', 
                               columns='platform', 
                               values='total_sales', 
                               aggfunc='sum'),
              markers=True, symbol='platform',
              title='Распределение общих продаж c 2013 по 2016 год',
              labels={'value':'общие продажи, млн. копий', 'year_of_release': 'год', 'platform':'платформа'})

fig.show()

In [35]:
data.query('year_of_release==2016').groupby('platform').total_sales.sum().sort_values(ascending=False).reset_index().style.bar()

In [36]:
last_years_platform_sales = data.groupby(['year_of_release', 'platform']).total_sales.sum().reset_index()

fig = go.Figure(data=go.Heatmap(name = 'Тепловая карта', 
                   z= last_years_platform_sales.total_sales,
                   x= last_years_platform_sales.platform,
                   y= last_years_platform_sales.year_of_release,
                   hovertemplate = 'платформа : %{x}<br>год : %{y}<br>общие продажи, млн. копий : %{z}',
                   hoverongaps = False))

fig.update_layout(title='Тепловая карта общих продаж игр в разбивке по платформам с 2013 по 2016 год',
                  xaxis_title='платформа', 
                  yaxis_title="год")

fig.show()

На фоне общего снижения продаж, на 2016 год все же больше общих продаж по платформам **PS4, XOne и 3DS**.

### График «ящик с усами» по глобальным продажам игр в разбивке по платформам

In [37]:
fig = px.box(data, 
             x='platform', 
             y='total_sales', 
             color='platform',
             labels={'platform':'платформа', 
                     'total_sales': 'общие продажи'}
            )

fig.update_layout(title='График «ящик с усами» по общим продажам игр в разбивке по платформам ',
                  xaxis_title='платформа', 
                  yaxis_title="общие продажи, млн. копий")

fig.show()

In [38]:
#Установим лимит по оси "y" и посмотрим поближе

fig = px.box(data, 
             x='platform', 
             y='total_sales', 
             color='platform',
             labels={'platform':'платформа', 
                    'total_sales': 'общие продажи'}
            )

fig.update_layout(title='График «ящик с усами» по общим продажам игр в разбивке по платформам ',
                  xaxis_title='платформа', 
                  xaxis_fixedrange=True,
                  yaxis_title="общие продажи, млн. копий", 
                  yaxis_range=[0, 1.7],
                  yaxis_fixedrange=True)

fig.update_traces(boxmean=True)

fig.show()

In [39]:
#Статистика общих продаж по платформам

fig = px.imshow(data.groupby('platform').total_sales.describe().drop('count', axis=1),      
                height=760, color_continuous_scale='balance',
                text_auto=True)

fig.update_layout(title_text='Статистика общих продаж по платформам с 2013 года', 
                  title_x=0.5, 
                  coloraxis_colorbar=dict(
                      thickness=12,
                      len=0.3) 
                 ) 
fig

По медианным значениям общих продаж лидируют платформы X360, XOne, PS4, WiiU, Wii от 0,26 до 0,18 млн.проданных копий, по ним же самые высокие средние значения, верхние границы "усов" 1,73 - 1,3 млн.проданных копий. Самые меньшие медианы продаж по платформам PSV - 0,04, PSP - 0,02 млн.проданных копий.

### Как влияют на продажи внутри одной популярной платформы отзывы пользователей и критиков
- Строим диаграмму рассеяния и считаем корреляцию между отзывами и продажами. Формулируем выводы.

Возьмем одну из самых популярных платформ в актуальном периоде PS3

In [40]:
#Диаграмма рассеяния для платформы PS3 - общие продажи - оценки критиков
fig = px.scatter(data.query('critic_score>-1 and platform=="PS3"'), 
                 x='critic_score', y='total_sales', trendline='ols',
                 title='Диаграмма рассеяния для платформы PS3 - общие продажи - оценки критиков')

fig.update_layout(xaxis_title='оценки критиков', 
                  yaxis_title="общие продажи, млн. копий")

fig.show()


#Диаграмма рассеяния для платформы PS3 - общие продажи - оценки пользователей
fig = px.scatter(data.query('user_score>-1 and platform=="PS3"'), 
                 x='user_score', y='total_sales', trendline='ols',
                 title='Диаграмма рассеяния для платформы PS3 - общие продажи - оценки пользователей')

fig.update_layout(xaxis_title='оценки пользователей', 
                  yaxis_title="общие продажи, млн. копий")

fig.show()

In [41]:
#Корреляция между отзывами и продажами PS3

print('Коэффициент корреляции между общими продажами и оценками критиков для платформы PS3 составляет :', 
      data.query('critic_score >-1 and platform=="PS3"'
                ).total_sales.corr(data.query('critic_score >-1 and platform=="PS3"')
                                                                          .critic_score).round(3))

print()

print('Коэффициент корреляции между общими продажами и оценками пользователей для платформы PS3 составляет :', 
      data.query('user_score >-1 and platform=="PS3"'
                ).total_sales.corr(data.query('user_score >-1 and platform=="PS3"')
                                                                          .user_score).round(3))

Коэффициент корреляции между общими продажами и оценками критиков для платформы PS3 составляет : 0.334

Коэффициент корреляции между общими продажами и оценками пользователей для платформы PS3 составляет : 0.002

Разброс оценок критиков меньше, чем разброс оценок пользователей, бОльшая часть оценок находится в области наименьших продаж.  Корреляции между величинами соответственно 0,33 и 0,002, т.е. оценки критиков влияют на продажи в большей степени, чем пользователей. Оценки пользователей почти не влияют на продажи.

### Сравнение выводов с продажами игр на других платформах

In [42]:
#Для анализа выберем 5 платформ с наибольшим количеством оценок критиков, исключаем уже рассмотренную PS3

critic_score_platforms = data.query('critic_score>-1 and platform!="PS3"'
                                   ).groupby('platform').critic_score.count().sort_values(ascending=False).head()

data.query('critic_score>-1'
          ).groupby('platform').critic_score.count().sort_values(ascending=False)

platform
PS4     252
XOne    169
PC      149
PS3     121
X360     81
PSV      77
3DS      71
WiiU     70
PSP       1
Name: critic_score, dtype: int64

In [43]:
#И с наибольшим количество оценок пользователей

user_score_platforms = data.query('user_score>-1 and platform!="PS3"'
                                 ).groupby('platform').user_score.count().sort_values(ascending=False).head()

data.query('user_score>-1'
          ).groupby('platform').user_score.count().sort_values(ascending=False)

platform
PS4     257
PS3     186
XOne    182
PC      155
X360    143
PSV      99
3DS      80
WiiU     80
Wii       7
PSP       2
DS        1
Name: user_score, dtype: int64

Это одни и те же платформы.

In [44]:
#Диаграммы рассеяния для выбранных платформ, общие продажи - оценки критиков

fig = px.scatter(data.query('critic_score>-1 and platform in @critic_score_platforms.index'), 
                 x='critic_score', 
                 y='total_sales', 
                 facet_col = 'platform', 
                 trendline='ols', 
                 trendline_color_override='crimson',
                 title='Диаграммы рассеяния для выбранных платформ, общие продажи - оценки критиков',
                 labels={'total_sales':'общие продажи, млн. копий', 
                         'critic_score': 'оценка критиков', 
                         'platform':'платформа'}
                )

fig.show()

#Диаграммы рассеяния для выбранных платформ, общие продажи - оценки пользователей
fig = px.scatter(data.query('user_score>-1 and platform in @user_score_platforms.index'), 
                 x='user_score', 
                 y='total_sales', 
                 facet_col = 'platform', 
                 trendline='ols', 
                 trendline_color_override='crimson',
                 title='Диаграммы рассеяния для выбранных платформ, общие продажи - оценки пользователей',
                 labels={'total_sales':'общие продажи, млн. копий', 
                         'user_score': 'оценка<br>пользователей', 
                         'platform':'платформа'}
                )

fig.show()

In [45]:
#Корреляция между отзывами критиков и пользователей и продажами по платформам

display(
    data.query('critic_score >-1 and platform in @critic_score_platforms.index').groupby('platform')\
    [['total_sales', 'critic_score']].corr()[['total_sales']].style.background_gradient(cmap='Blues'),
        
    data.query('user_score >-1 and platform in @user_score_platforms.index').groupby('platform')\
    [['total_sales', 'user_score']].corr()[['total_sales']].style.background_gradient(cmap='Blues'))

Разброс оценок критиков меньше, чем разброс оценок пользователей, и имеет тенденцию увеличения величины оценки с увеличением объема продаж. 

Все коэффициенты корреляции говорят о слабых и очень слабых связях по шкале Чеддока между общими продажами и оценками пользователей / критиков.

Коэффициенты корреляции между оценками критиков и общими продажами по платформам X360, PS4, XOne и PS3 примерно схожи - 0,42 - 0,33. Значения коэффициентов корреляции между оценками пользователей и общими продажами очень малы, есть отрицательные значения. Оценки критиков влияют на продажи, пусть не сильно, но в бОльшей степени, чем оценки пользователей.

### Общее распределение игр по жанрам
- Что можно сказать о самых прибыльных жанрах? Выделяются ли жанры с высокими и низкими продажами?

In [46]:
genre_sales = data.groupby('genre').agg({'name': 'count', 'total_sales': 'sum'}
                                       ).sort_values(by = 'total_sales', ascending=False
                                                    ).rename(columns = {'name':'number_of_games'})

genre_sales.style.bar()

In [47]:
trace1 = go.Bar(
    x=genre_sales.index,
    y=genre_sales.number_of_games,
    name='Количество игр')

trace2 = go.Bar(
    x=genre_sales.index,
    y=genre_sales.total_sales,
    name='Общие продажи',
    marker_color='crimson')

layout = {'title': 'Распределение общих продаж и количества игр по жанрам с 2013 по 2016 год', 
          'xaxis': {'title': 'название жанра'},
          'yaxis': {'title': 'количество игр | продажи'}}

fig = go.Figure(data=[trace1, trace2], layout=layout)
fig.show()

In [48]:
#Доля игр в этом жанре от общего числа игр
genre_sales['games_share'] = genre_sales['number_of_games']/genre_sales['number_of_games'].sum()*100

#Доля продаж от общего числа продаж
genre_sales['sales_share'] = genre_sales['total_sales']/genre_sales['total_sales'].sum()*100

#Количество проданных копий на колличество игр в жанре
genre_sales['sales_per_games'] = genre_sales['total_sales']/genre_sales['number_of_games'] *100

genre_sales.sort_values(by='sales_per_games', ascending=False, inplace=True)
genre_sales.style.bar()

In [49]:
trace1 = go.Bar(
    x=genre_sales.index,
    y=genre_sales.sales_per_games,
    name='Удельные продажи',
    marker_color='limegreen')

trace2 = go.Bar(
    x=genre_sales.index,
    y=genre_sales.total_sales,
    name='Общие продажи',
    marker_color='crimson')

layout = {'title': 'Распределение суммарных продаж и удельных продаж по жанрам с 2013 по 2016 год', 
          'xaxis': {'title': 'название жанра'},
          'yaxis': {'title': 'продажи | удельные продажи'}}

fig = go.Figure(data=[trace1, trace2], layout=layout)
fig.show()

По абсолютным величинам общих продаж на первом месте Action, далее Sports и Shooter, последние места занимают Adventure, Puzzle и Strategy. По удельным величинам - объему продаж на количество выпущенных игр, жанр Shooter выходит на первое место, далее Sports и Platform, в середине Racing, Fighting, Action и Misc. И самые последние Puzzle, Strategy и Adventure.

Для прибыльности нам нужны стабильные жанры, которые приносят доход независимо от платформы, значит на этот жанр есть устойчивый спрос.

In [50]:
#График «ящик с усами» по глобальным продажам игр в разбивке по жанрам

fig = px.box(data, 
             x='genre', 
             y='total_sales', 
             color='genre',
             labels={'genre':'название жанра', 
                     'total_sales': 'общие продажи'})

fig.update_layout(title='График «ящик с усами» по общим продажам игр в разбивке по жанрам с 2013 по 2016 год',
                  xaxis_title='название жанра', 
                  yaxis_title="общие продажи, млн. копий")

fig.show()

In [51]:
#Установим лимит по оси "y" и посмотрим ближе

fig = px.box(data, 
             x='genre', 
             y='total_sales', 
             color='genre',
             labels={'genre':'название жанра', 
                     'total_sales': 'общие продажи'})

fig.update_layout(title='График «ящик с усами» по общим продажам игр в разбивке по жанрам с 2013 по 2016 год',
                  xaxis_title='название жанра', 
                  xaxis_fixedrange=True,
                  yaxis_title="общие продажи, млн. копий", 
                  yaxis_range=[0, 1.7],
                  yaxis_fixedrange=True)

fig.update_traces(boxmean=True)

fig.show()

По устойчивости спроса выделяются жанры Shooter, Sports и Platform.

## Портрет пользователя каждого региона

Определяем для пользователя каждого региона (NA, EU, JP):
- Самые популярные платформы (топ-5). Описание различия в долях продаж.
- Самые популярные жанры (топ-5). Поясним разницу.
- Влияет ли рейтинг ESRB на продажи в отдельном регионе?

### Самые популярные платформы в регионах

In [52]:
#Объединяем менее популярные платформы в одну группу, предварительно выбрав топ-5 платформ по каждому региону 

#Северная Америка

top_platform_na_sales = data.groupby('platform').na_sales.sum().sort_values(ascending=False).head()
platform_na_sales = data.groupby('platform').na_sales.sum().sort_values(ascending=False).reset_index()

platform_na_sales['platform'] = platform_na_sales['platform']\
.where(platform_na_sales['platform'].isin(top_platform_na_sales.index), 'Other')

In [53]:
platform_na_sales = platform_na_sales.groupby('platform').na_sales.sum().reset_index()

In [54]:
#Европа

top_platform_eu_sales = data.groupby('platform').eu_sales.sum().sort_values(ascending=False).head()
platform_eu_sales = data.groupby('platform').eu_sales.sum().sort_values(ascending=False).reset_index()

platform_eu_sales['platform'] = platform_eu_sales['platform']\
.where(platform_eu_sales['platform'].isin(top_platform_eu_sales.index), 'Other')

In [55]:
platform_eu_sales = platform_eu_sales.groupby('platform').eu_sales.sum().reset_index()

In [56]:
#Япония

top_platform_jp_sales = data.groupby('platform').jp_sales.sum().sort_values(ascending=False).head()
platform_jp_sales = data.groupby('platform').jp_sales.sum().sort_values(ascending=False).reset_index()

platform_jp_sales['platform'] = platform_jp_sales['platform']\
.where(platform_jp_sales['platform'].isin(top_platform_jp_sales.index), 'Other')

In [57]:
platform_jp_sales = platform_jp_sales.groupby('platform').jp_sales.sum().reset_index()

In [58]:
#Сводная таблица для регионов

platform_regional_sales = platform_na_sales.merge(platform_eu_sales, how='outer').merge(platform_jp_sales, how='outer')
platform_regional_sales

  platform  na_sales  eu_sales  jp_sales
0      3DS     38.20     30.96     67.81
1    Other     52.49     58.26      4.19
2      PS3     63.50     67.81     23.35
3      PS4    108.74    141.09     15.96
4     X360     81.66     42.52       NaN
5     XOne     93.12     51.59       NaN
6      PSV       NaN       NaN     18.59
7     WiiU       NaN       NaN     10.88

In [59]:
#Строим круговые диаграммы долей продаж по платформам для каждого региона

fig = make_subplots(rows=1, 
                    cols=3, 
                    specs=[[{'type':'domain'}, {'type':'domain'}, {'type':'domain'}]]
                   )
fig.add_trace(go.Pie(labels=platform_regional_sales.platform, 
                     values=platform_regional_sales.na_sales, 
                     name="NA Sales", textinfo='label+percent', 
                     insidetextorientation='horizontal'),
              1, 1)

fig.add_trace(go.Pie(labels=platform_regional_sales.platform, 
                     values=platform_regional_sales.eu_sales, 
                     name="EU Sales", textinfo='label+percent', 
                     insidetextorientation='horizontal'),
              1, 2)

fig.add_trace(go.Pie(labels=platform_regional_sales.platform, 
                     values=platform_regional_sales.jp_sales, 
                     name="JP Sales", textinfo='label+percent', 
                     insidetextorientation='horizontal'),
              1, 3)

fig.update_layout(
    
    title_text="Региональные продажи по платформам с 2013 по 2016 год",
    annotations=[dict(text='NA Sales', x=0.1, y=1, font_size=20, showarrow=False),
                 dict(text='EU Sales', x=0.5, y=1, font_size=20, showarrow=False),
                 dict(text='JP Sales', x=0.9, y=1, font_size=20, showarrow=False)])

fig.show()

В региональных продажах по Северной Америке лидирует платформа PS4 с долей в региональных продажах 24,8%, далее XOne - 21,3%, X360 - 18,7%, PS3 - 14,5%, объединенная группа платформ, не попавших в топ-5 по региону - 12% и 3DS - 8,73%.

В европейских продажах первое место занимает PS4 - 36%, затем PS3 - 17,3%, "Другие" - 14,9%, XOne - 13,2%, X360 - 10,8% и 3DS - 7,89%.

В Японии бОльшая доля продаж приходится на 3DS - 48,2%, намного меньше на PS3 - 16,6%, PSV - 13,2%, PS4 - 11,3%, WiiU - 7,73, и "Другие" - всего 2,98%.

### Самые популярные жанры в регионах

In [60]:
#Объединяем менее популярные жанры в одну группу, предварительно выбрав топ-5 жанров по каждому региону 

#Северная Америка

top_genre_na_sales = data.groupby('genre').na_sales.sum().sort_values(ascending=False).head()
genre_na_sales = data.groupby('genre').na_sales.sum().sort_values(ascending=False).reset_index()

genre_na_sales['genre'] = genre_na_sales['genre']\
.where(genre_na_sales['genre'].isin(top_genre_na_sales.index), 'Other')

In [61]:
genre_na_sales = genre_na_sales.groupby('genre').na_sales.sum().reset_index()

In [62]:
#Европа

top_genre_eu_sales = data.groupby('genre').eu_sales.sum().sort_values(ascending=False).head()
genre_eu_sales = data.groupby('genre').eu_sales.sum().sort_values(ascending=False).reset_index()

genre_eu_sales['genre'] = genre_eu_sales['genre']\
.where(genre_eu_sales['genre'].isin(top_genre_eu_sales.index), 'Other')

In [63]:
genre_eu_sales = genre_eu_sales.groupby('genre').eu_sales.sum().reset_index()

In [64]:
#Япония

top_genre_jp_sales = data.groupby('genre').jp_sales.sum().sort_values(ascending=False).head()
genre_jp_sales = data.groupby('genre').jp_sales.sum().sort_values(ascending=False).reset_index()

genre_jp_sales['genre'] = genre_jp_sales['genre']\
.where(genre_jp_sales['genre'].isin(top_genre_jp_sales.index), 'Other')

In [65]:
genre_jp_sales = genre_jp_sales.groupby('genre').jp_sales.sum().reset_index()

In [66]:
#Сводная таблица для регионов

genre_regional_sales = genre_na_sales.merge(genre_eu_sales, how='outer').merge(genre_jp_sales, how='outer')
genre_regional_sales

          genre  na_sales  eu_sales  jp_sales
0        Action    126.05    118.13     40.49
1          Misc     27.49       NaN      9.20
2         Other     62.76     68.56     25.79
3  Role-Playing     46.40     36.97     51.04
4       Shooter    109.74     87.86      6.61
5        Sports     65.27     60.52       NaN
6        Racing       NaN     20.19       NaN
7      Fighting       NaN       NaN      7.65

In [67]:
#Строим круговые диаграммы долей продаж по жанрам для каждого региона

fig = make_subplots(rows=1, 
                    cols=3, 
                    specs=[[{'type':'domain'}, {'type':'domain'}, {'type':'domain'}]]
                   )
fig.add_trace(go.Pie(labels=genre_regional_sales.genre, 
                     values=genre_regional_sales.na_sales, 
                     name="NA Sales", textinfo='label+percent', 
                     insidetextorientation='horizontal'),
              1, 1)

fig.add_trace(go.Pie(labels=genre_regional_sales.genre, 
                     values=genre_regional_sales.eu_sales, 
                     name="EU Sales", textinfo='label+percent', 
                     insidetextorientation='horizontal'),
              1, 2)

fig.add_trace(go.Pie(labels=genre_regional_sales.genre, 
                     values=genre_regional_sales.jp_sales, 
                     name="JP Sales", textinfo='label+percent', 
                     insidetextorientation='horizontal'),
              1, 3)

fig.update_layout(
    title_text="Региональные продажи по жанрам с 2013 по 2016 год",
    annotations=[dict(text='NA Sales', x=0.1, y=1, font_size=20, showarrow=False),
                 dict(text='EU Sales', x=0.5, y=1, font_size=20, showarrow=False),
                 dict(text='JP Sales', x=0.9, y=1, font_size=20, showarrow=False)])

fig.show()

В Северное Америке самые популярные жанры в порядке убывания Action - 28,8%, Shooter, Sports, общая группа, не вошедших в топ-5 жанров - 14,3%, Role-Playing и Misc.

В Европе - это Action - 30,1%, Shooter, "Другие", Sports, Role-Playing и Racing.

По продажам в Японии лидирует Role-Playing - 36,3%, затем Action, "Другие" - 18,3%, Misc, Fighting и Shooter.

### Влияние рейтинга ESRB на продажи в отдельном регионе

In [68]:
#Региональные продажи игр с разным рейтингом ESRB

rating_na_sales = data.groupby('rating').na_sales.sum().sort_values(ascending=False).reset_index()
rating_eu_sales = data.groupby('rating').eu_sales.sum().sort_values(ascending=False).reset_index()
rating_jp_sales = data.groupby('rating').jp_sales.sum().sort_values(ascending=False).reset_index()

rating_regional_sales = rating_na_sales.merge(rating_eu_sales, how='outer').merge(rating_jp_sales, how='outer')

rating_regional_sales

      rating  na_sales  eu_sales  jp_sales
0          M    165.21    145.32     14.11
1  no rating     89.42     78.91     85.05
2          E     79.05     83.36     15.14
3       E10+     54.24     42.69      5.89
4          T     49.79     41.95     20.59

In [69]:
#Строим круговые диаграммы долей продаж по рейтингу для каждого региона

fig = make_subplots(rows=1, 
                    cols=3, 
                    specs=[[{'type':'domain'}, {'type':'domain'}, {'type':'domain'}]]
                   )
fig.add_trace(go.Pie(labels=rating_regional_sales.rating, 
                     values=rating_regional_sales.na_sales, 
                     name="NA Sales", textinfo='label+percent', 
                     insidetextorientation='horizontal'),
              1, 1)

fig.add_trace(go.Pie(labels=rating_regional_sales.rating, 
                     values=rating_regional_sales.eu_sales, 
                     name="EU Sales", textinfo='label+percent', 
                     insidetextorientation='horizontal'),
              1, 2)

fig.add_trace(go.Pie(labels=rating_regional_sales.rating, 
                     values=rating_regional_sales.jp_sales, 
                     name="JP Sales", textinfo='label+percent', 
                     insidetextorientation='horizontal'),
              1, 3)

fig.update_layout(
    title_text="Региональные продажи по рейтингу ESRB с 2013 по 2016 год",
    annotations=[dict(text='NA Sales', x=0.1, y=1, font_size=20, showarrow=False),
                 dict(text='EU Sales', x=0.5, y=1, font_size=20, showarrow=False),
                 dict(text='JP Sales', x=0.9, y=1, font_size=20, showarrow=False)])

fig.show()

В Северной Америке больше всего продаются игры с рейтингом "17+", затем следуют игры без рейтинга, для всех возрастов, для возраста "10+" и для подростков "13+".

По Европе также больше продаж игр с рейтингом "17+", для всех возрастов, без рейтинга,  для возраста 10+ и для подростков.

В Японии продажи игр, не имеющих американского рейтинга составляют 60,4%, далее следуют игры для подростков 13+, с рейтингом "для всех", 17+ и 10+.


Пропуски рейтинга в данном случае означают, что игра имеет другой рейтинг и выпускалась не в Северной Америке.

## Проверка гипотезы
- Средние пользовательские рейтинги платформ Xbox One и PC одинаковые
- Средние пользовательские рейтинги жанров Action и Sports разные

### Средние пользовательские рейтинги платформ Xbox One и PC одинаковые

Для проверки гипотез будем использовать t-критерий Стьюдента, так как выборки между собой независимы.
Определим значение уровня значимости alpha = 0.05

*Нулевая гипотеза*

H_0: Средний пользовательский рейтинг платформы Xbox One = средний пользовательский рейтинг платформы PC 

*Альтернативная гипотеза*

H_1: Средний пользовательский рейтинг платформы Xbox One ≠ средний пользовательский рейтинг платформы PC

In [70]:
print('Cредний пользовательский рейтинг платформы Xbox One: ', data.query('platform=="XOne" & user_score>-1').user_score.mean())
print('Cредний пользовательский рейтинг платформы PC: ', data.query('platform=="PC" & user_score>-1').user_score.mean())
print()

results = st.ttest_ind(
    data[(data['platform'] == 'XOne') & (data['user_score'] > -1)]['user_score'], 
    data[(data['platform'] == 'PC') & (data['user_score'] > -1)]['user_score'], equal_var = False)   

alpha = 0.05  

print('p-значение:', results.pvalue)

if results.pvalue < alpha:
    print('Отвергаем нулевую гипотезу')
else:
    print('Не получилось отвергнуть нулевую гипотезу')

Cредний пользовательский рейтинг платформы Xbox One:  6.521428571428572
Cредний пользовательский рейтинг платформы PC:  6.2696774193548395

p-значение: 0.14759594013430463
Не получилось отвергнуть нулевую гипотезу

Средние пользовательские рейтинги не равны, однако вероятность случайно получить такое или большее различие достаточно велика и состаляет примерно 15%, различия между средними не значимы и нулевая гипотеза не отвергается.

### Средние пользовательские рейтинги жанров Action и Sports разные

Для проверки гипотез в этом случае также будем использовать t-критерий Стьюдента, так как выборки между собой независимы.
Определим значение уровня значимости alpha = 0.05.

Нулевая гипотеза формулируется как равенство независимо от того, как сформулирован вопрос - в виде отрицания или утверждения.

*Нулевая гипотеза*

H_0: Средний пользовательский рейтинг жанра Action = средний пользовательский рейтинг жанра Sports

*Альтернативная гипотеза*

H_1: Средний пользовательский рейтинг жанра Action ≠ средний пользовательский рейтинг жанра Sports

In [71]:
print('Cредний пользовательский рейтинг жанра Action: ', data.query('genre=="Action" & user_score>-1').user_score.mean())
print('Cредний пользовательский рейтинг жанра Sports: ', data.query('genre=="Sports" & user_score>-1').user_score.mean())
print()

results = st.ttest_ind(
    data[(data['genre'] == 'Action') & (data['user_score'] > -1)]['user_score'], 
    data[(data['genre'] == 'Sports') & (data['user_score'] > -1)]['user_score'], equal_var = False)   

alpha = 0.05  

print('p-значение:', results.pvalue)

if results.pvalue < alpha:
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")

Cредний пользовательский рейтинг жанра Action:  6.837532133676092
Cредний пользовательский рейтинг жанра Sports:  5.238124999999999

p-значение: 1.4460039700704318e-20
Отвергаем нулевую гипотезу

**Вывод:**

Средний пользовательский рейтинг платформы Xbox One и средний пользовательский рейтинг платформы PC одинаковы.

Средний пользовательский рейтинг жанра Action и средний пользовательский рейтинг жанра Sports разные.

## Общий вывод

**В результате анализа исходных данных установили следующее:**

- Жизненный цикл платформы с момента выхода на рынок до вытеснения новым продуктом составляет примерно 9-10 лет.
- Для построения прогноза на 2017 год, был взят актуальный период, начиная с 2013 года.


- На фоне общего снижения продаж, на 2016 год все же больше общих продаж по платформам PS4, XOne и 3DS. По медианным значениям общих продаж лидируют платформы X360, XOne, PS4, WiiU, Wii от 0,26 до 0,18 млн.проданных копий, по ним же самые высокие средние значения, верхние границы "усов" 1,73 - 1,3 млн.проданных копий. Самые меньшие медианы продаж по платформам PSV - 0,04, PSP - 0,02 млн.проданных копий.


- Для оценки влияния рейтингов критиков и пользователей на продажи взята одна из популярных платформ в PS3: рассеяние диаграммы продажи - оценка критиков более сконцентрировано, чем диаграммы продажи - оценка пользователей, соответственно корреляции между величинами - 0,33 и 0,002, т.е. оценки критиков влияют на продажи в большей степени, чем пользователей. Оценки пользователей почти не влияют на продажи.


- Для платформ с наибольшим количеством оценок от критиков и пользователей PS4, XOne, PC, X360, PSV: разброс оценок критиков меньше, чем разброс оценок пользователей, и имеет тенденцию увеличения величины оценки с увеличением объема продаж. Коэффициенты корреляции между оценками критиков и общими продажами по платформам X360, PS4, XOne и PS3 примерно схожи - 0,42 - 0,33. Значения коэффициентов корреляции между оценками пользователей и общими продажами очень малы, есть отрицательные значения. Оценки критиков влияют на продажи, пусть не сильно, но в гораздо бОльшей степени, чем оценки пользователей.

 
- По абсолютным величинам общих продаж на первом месте Action, далее Sports и Shooter, последние места занимают Adventure, Puzzle и Strategy. По удельным величинам - объему продаж на количество выпущенных игр, жанр Shooter выходит на первое место, далее Sports и Platform, в середине Racing, Fighting, Action и Misc. И самые последние Puzzle, Strategy и Adventure. По прибыльности выделяются жанры Shooter, Sports и Platform.


**Региональная специфика продаж:**


- *Северная Америка*

В региональных продажах по Северной Америке лидирует платформа PS4 с долей в региональных продажах 24,8%, далее XOne - 21,3%, X360 - 18,7%, PS3 - 14,5%, объединенная группа платформ, не попавших в топ-5 по региону - 12% и 3DS - 8,73%.

Самые популярные жанры в порядке убывания Action - 28,8%, Shooter, Sports, общая группа, не вошедших в топ-5 жанров - 14,3%, Role-Playing и Misc.

Больше всего продаются игры с рейтингом "17+", затем следуют игры без рейтинга, для всех возрастов, для возраста "10+" и для подростков "13+".

- *Европа*

В европейских продажах первое место занимает PS4 - 36%, затем PS3 - 17,3%, "Другие" - 14,9%, XOne - 13,2%, X360 - 10,8% и 3DS - 7,89%.

Самые популярные жанры в Европе - это Action - 30,1%, далее Shooter, "Другие", Sports, Role-Playing и Racing.

По Европе также больше продаж игр с рейтингом "17+", для всех возрастов, без рейтинга, для возраста 10+ и для подростков.

- *Япония*

В Японии бОльшая доля продаж приходится на 3DS - 48,2%, намного меньше на PS3 - 16,6%, PSV - 13,2%, PS4 - 11,3%, WiiU - 7,73, и "Другие" - всего 2,98%.

Популярные жанры в порядке убывания Role-Playing - 36,3%, затем Action, "Другие" - 18,3%, Misc, Fighting и Shooter.

Продажи игр, не имеющих американского рейтинга составляют 60,4%, далее следуют игры для подростков 13+, с рейтингом "для всех", 17+ и 10+.


- **Проверены гипотезы:**

Средние пользовательские рейтинги платформ Xbox One и PC одинаковые

Средние пользовательские рейтинги жанров Action и Sports разные


- и установлено, что:

Средний пользовательский рейтинг платформы Xbox One и средний пользовательский рейтинг платформы PC одинаковы.


Средний пользовательский рейтинг жанра Action и средний пользовательский рейтинг жанра Sports разные.